### ISSUE TITLE
MindPalace: Item Selection

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuestAssets#13]
ITEM SELECTION

As Per (MindPalace Interaction Design #12)
Will need a total of 8 interactable spots that are initially empty. 
Player needs to activate 4/8 spots to progress to next level (Portal Opens)

If player is near a spot (or perhaps looks at a spot with camera in case if they can't physically reach the spot), a square, slightly opaque shape will appear over spot and player can press button/click/tap to activate interactable spot. Once spot is activated, first random object appears in spot. Player can then cycle through different items one at a time using arrow keys/WASD/tap on item, which will show up in the spot in 3d space.

- Name of object appears underneath object in 3d space.
- Can click on a checkmark icon to accept new object or an 'x' icon to exit out of interaction.
- An interactable spot could also be an NPC you can talk to. 

![interactables_thumbnail](https://user-images.githubusercontent.com/6446247/50435795-a69e8000-0897-11e9-8409-b139266a92c3.jpg)

**Comment by michaelmendoza** [comment]
Started work on Interactable ItemSelection. Click on Interactable Object to make Selection Buttons appear. Then click on left and right buttons to change interactable. Work in Progress.

<img width="332" alt="screen shot 2019-01-08 at 1 58 47 pm" src="https://user-images.githubusercontent.com/4431065/50858403-8f5a9a80-134d-11e9-9bda-b4f24ed3f76b.png">

<img width="360" alt="screen shot 2019-01-08 at 1 57 00 pm" src="https://user-images.githubusercontent.com/4431065/50858363-6a662780-134d-11e9-8ee8-3133fd249a65.png">
<img width="374" alt="screen shot 2019-01-08 at 1 57 06 pm" src="https://user-images.githubusercontent.com/4431065/50858364-6a662780-134d-11e9-802c-1023d67f9f87.png">
