### ISSUE TITLE
MindPalace: Narrative NPC/Prompt UI

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuestAssets#14]
NARRATIVE

Need UI Programming support for following prompt and NPC interactable as per (MindPalace Interaction Design Issue #12):

-Option for Prompt to show up when you first enter a Level. (Prompt: "It's almost dinner! Get the restaurant ready for business.") This is open ended - no need for a win/fail state, this just helps gets the player in the mindframe of selecting specific objects. 

-Option for a Question/Answer interactable with NPC. (Q:"Have you heard the news?" A:"It'll be hailing today." "I don't care." "Your dog loves cheese?" "Judy can limbo!") (NPC can respond depending on answer) 

Steps:
- Player approaches NPC, who will have a glowing outline to indicate that they can be selectable. 
- Player taps on/clicks on NPC. NPC asks a question or says a statement, Player can choose a random response. Player can also choose to leave NPC alone by click/tap on "x" symbol or confirm answer with checkmark symbol. 
- NPC will have Response Bubble to Player input. Player's Answer Bubble will still remain visible so long as they don't move. 
- When Player moves, Player Answer Bubble will disappear, but NPC Response Bubble will remain unless player is a little too far away from them. NPC's Response Bubble will show up if player is in range. 
- Can repeat this interactable if Player taps/clicks on NPC again - shows the responses again like in Step 3 in thumbnail below. Player has option to exit by hitting "x" button. 
![interactablesnpc_thumbnail](https://user-images.githubusercontent.com/6446247/50437553-0d736780-089f-11e9-9713-f9a2d063711c.jpg)

**Comment by michaelmendoza** [comment]
Update Dialog design

![interactablesnpc_thumbnail_simple](https://user-images.githubusercontent.com/4431065/52704531-03d0bc80-2f3e-11e9-9b63-66070e094e29.jpg)
