### ISSUE TITLE
MindPalace: Winning State 

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuestAssets#15]
As Per (MindPalace Interaction Design #12 ) 

Will need support to have a "winning state" of sorts. Goal is for player to confirm 4/8 interactables (either by selecting objects or answers to NPC Interactables). As soon as player finds the 4th object, a portal (could be simple circle that floats/funky colors/etc) opens in middle of room. 

Player can walk through portal, but player can tap/select portal to bring up prompt asking if player memorized objects and wants to leave ("Are you finished rehearsing here?"). 

If Yes, kicks you to level select (not hub). No = stay in level, portal remains.

**Comment by michaelmendoza** [comment]
Added EndGameUI for Winning State: 

![image](https://user-images.githubusercontent.com/4431065/53531276-fd9b1e00-3aaf-11e9-9b18-c13b5fe042e8.png)
