### ISSUE TITLE
Prototype: Create a survey for SeedQuestPrototypes

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuestAssets#22]
Create an in game survey for SeedQuest prototypes. At end of In-game survey, the survey data is sent though an API to surveymonkey or some simple backend survey data point.  

Possible Questions:
What is your overall impression of the game? 
What's your overall impression of the interface: what's convenient, inconvenient, odd, etc?
Which of the game prototypes was the most memorable?
Which of the game prototypes was the most interactive and fun to play?
If you had a magic wand, what changes would you like to see in the gameplay?
What kinds of themes or items would you like to see added to the gameplay? 
How likely or unlikely would they be to use this product once it’s finished?

**Comment by westonb7** [comment]
Possible questions: 

Was it easy to navigate through the environment?
Which environment looked most visually appealing to you?
If you could add your own environment to the game, what would you add?

**Comment by ntelfer** [comment]
Core goals of this iteration are:

- Identify which prototypes to move forward with.
- Start to understand which prototypes are easiest to remember.

Streamlining of the survey and game will come later.

**Comment by cameronthughes** [comment]
Was the goal clear?
Did you understand the controls?
Which device would you prefer to use for this experience? (PC/Mobile/Game Controller)
Did you feel like it took too long, and/or not long enough?
Did selecting items feel intuitive? 
How would you like to select items?
Were you satisfied with the amount of options you had?
Was it clear how to make your choices?

**Comment by BradyHammond** [comment]
If you could choose the art style of the game, what would it be?
Would you prefer to play the game from a different camera view?
What did you like most about the game?
What did you like least about the game?
How long did it take to complete each game?

**Comment by SmithSamuelM** [comment]
Which of the five concept did you like the best? worst?
Which of the five concepts was easiest to navigate? Hardest?
Which of the five concepts helped you learn the seed the best? worst?

Rating is a big ask unless its a simple check box
Rate the five concepts from best to worst in how you liked them overall. (check boxes)
Rate the five concepts from best to worst in how easy they were to navigate
Rate the five concepts from best to worst in how easy you learned the seed.

**Comment by SmithSamuelM** [comment]
If the question is phrased as rank the concepts from 1 to 5 with 1 being the most preferred and 5 being the least preferred (ties allowed) then it will condition the minds of the answerers to treat it as a ranking not a rating.    But if ties are allowed then the the data collection controls are no different then a rating. For each question, each concept has a row and  each row has the concept name followed by radio buttons 1 to 5 only one radio button on each row can be selected at a time.

**Comment by michaelmendoza** [comment]
Survey Complete
