### ISSUE TITLE
3P Mindpalace: Interactable Item Selection Fix

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuestAssets#25]
Currently, when a user selects an object and tries to cycle through items, they select the arrows with the cursor. This creates a user experience problem where visually the user focuses most on trying to click on the arrow and then has to look down/up at the changed object, instead of focusing on just the object. 

A solution would be to have the option to click on the item that needs to be changed instead of just the arrow buttons. This way, player can focus on the item that they're changing as well as quickly cycle through the item. Sometimes the item will be a part of something larger, for example axe or sword on a stump - would need a way to be able to include the stump as a part of the clickable interactable mesh too so the player doesn't have a hard time trying to select the axe/sword.

**Comment by michaelmendoza** [comment]
You can now click on the interactable to go to the next action. To be able to include something larger as part of the interactable. All you have to do is add another box collider, and make sure it bounds want ever you want to click on.
