### ISSUE TITLE
Prototype Survey - Prototype Select UI

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuestAssets#29]
### Tasks
- Create a Select Prototype Scene (@michaelmendoza)
- Create text blurb of Level Description (@jasukim @cameronthughes)
- Add Images of Level (800 x 450px) (@jasukim @cameronthughes )

###  **Will need a Select Prototype screen for the Survey.** 

Select between five prototypes 
- Seedquest
- Cliffside
- Laboratory
- Mind Palace
- Flatlands 

### **Will need text blurbs**
Please comment on issue with Level Descriptions. 1-2 sentences describing gameplay.

### **UI Asset Location**
I have provided UI assets as well as an example page:
Assets>PrototypeAssets>UI>PrototypeSelect

PrototypeSelect_UI_Button.png
PrototypeSelect_UI_Button_Levelhighlight.png
PrototypeSelect_UI_Level_Flatlands.png
PrototypeSelect_00_Example.png (shows layout)
PrototypeSelect_01_ExampleControls.png (shows what happens when you hit control button)

**Comment by jasukim** [comment]
### Example of UI Layout

![prototypeselect_00_example](https://user-images.githubusercontent.com/6446247/51647819-1d7c7680-1f33-11e9-8870-75a4ed181ca8.png)
![prototypeselect_01_examplecontrols](https://user-images.githubusercontent.com/6446247/51647822-20776700-1f33-11e9-96f4-e7ae483d4831.png)

**Comment by jasukim** [comment]
### **Text Blurbs for Level Description** - let me know if it sounds too redundant/repetitive or if it works for the prototype. Going for an explanation of the game's visual style (Isometric vs Third Person) and the purpose (remember the order of the objects/which objects you've selected) 

Welcome to Flatlands!
Explore the Wild West Saloon and Nonna's Restaurant in Flatlands! This is an isometric style memory game. Set the scene up however you like - make sure to remember the order of objects!

Welcome to Mind Palace!
Explore the verdant Campgrounds and Nonna's Restaurant in Mind Palace! This is a third person style memory game. Set the scene up however you like - just make sure to remember the order of objects!

**Comment by cameronthughes** [comment]
Welcome to Memory Laboratory!
The Memory Laboratory is a First Person experience. Experiment with the different objects in the environment to your liking. Be careful to remember the order and how you set everything up.

Controls
Move: WASD keys and move mouse to look around.
Select Object: Left Mouse Click 
Exit Level/Choose Level: ESC key on keyboard

Welcome to Cliff side
Cliff side is a place of magic and wonder. Interact with items nearby and use the map to find your way to other cliff side locations. 

Controls
Move: WASD keys and move mouse to look around.
Select Object: Left Mouse Click Item/Label to interact.
Exit Level/Choose Level: ESC Key on keyboard.

**Comment by cameronthughes** [comment]
![lab_ls](https://user-images.githubusercontent.com/10523510/51697856-0cc91080-1fc6-11e9-9efb-61ced8e17460.png)
![cliffside_ls](https://user-images.githubusercontent.com/10523510/51697857-0cc91080-1fc6-11e9-929b-c5df70d09ebc.png)

**Comment by jasukim** [comment]
Prototype Images for Flatlands and Mind Palace
![prototypeselect_ui_level_flatlands_01](https://user-images.githubusercontent.com/6446247/51772932-30618900-20a2-11e9-939c-e73d223c0cd6.png)


![prototypeselect_ui_level_mindpalace](https://user-images.githubusercontent.com/6446247/51765792-a3acd000-208d-11e9-9153-42bf10bdcc5f.png)

**Comment by michaelmendoza** [comment]
Completed PrototypeSelect Scene. Updated in SeedQuest Sandbox.

**Comment by michaelmendoza** [comment]
![demoselect](https://user-images.githubusercontent.com/4431065/51794610-7c402b00-2193-11e9-975b-1dbf376a4fce.gif)
