### ISSUE TITLE
Prototype: Next Interactable UI Visual

### ISSUE THREAD

**Issue by jasukim** [reputage/seedQuestAssets#31]
Currently we need a Next Interactable UI. Here's an example of what we're going for: 

![nextint_ui_example](https://user-images.githubusercontent.com/6446247/51776436-0910b900-20ae-11e9-8a2b-57385bd70ec1.png)

Included assets in this Issue: 
NextInt_UI_Bubble.png
NextInt_UI_Arrow.png
NextInt_UI_BubbleBorder.png

**Comment by jasukim** [comment]
UI Asset Images - White border should align with the blue bubble perfectly if you move by the center. I've also provided a thicker bubble width if that's easier to use/more aesthetically pleasing.

![nextint_ui_bubble_border](https://user-images.githubusercontent.com/6446247/51776621-e632d480-20ae-11e9-8e99-e4c9b52a229d.png)
![nextint_ui_arrow](https://user-images.githubusercontent.com/6446247/51776622-e632d480-20ae-11e9-8670-a22f05edc0e1.png)
![nextint_ui_bubble](https://user-images.githubusercontent.com/6446247/51776623-e6cb6b00-20ae-11e9-972e-32e3b7f71e30.png)
![nextint_ui_bubble_border_thick](https://user-images.githubusercontent.com/6446247/51776725-3c077c80-20af-11e9-8b37-ce46967fc3eb.png)

**Comment by michaelmendoza** [comment]
Next InteractablePreview Added:

![image](https://user-images.githubusercontent.com/4431065/53531352-494dc780-3ab0-11e9-9ba8-1c3237b63552.png)
