### ISSUE TITLE
Third-Person Camera Script

### ISSUE THREAD

**Issue by michaelmendoza** [reputage/seedQuestAssets#8]
- Create third person script that follows a character. 
- Controller for the person to move.

**Comment by jasukim** [comment]
![playermovement_thumbnail](https://user-images.githubusercontent.com/6446247/50438219-deaac080-08a1-11e9-9f35-62bc3e404697.jpg)
Diagram of rough camera placement and how player could move in space.

**Comment by michaelmendoza** [comment]
Complete for desktop, not for mobile
