### ISSUE TITLE
Lock in/Selecting mode

### ISSUE THREAD

**Issue by cameronthughes** [reputage/seedQuestAssets#9]
There needs to be a trigger event that makes the character go into a "Selection Mode". This is where the Characteres viewing angle is locked to 180 degrees and translations are locked and or limited to help them select stuff.

**Comment by michaelmendoza** [comment]
Copied from discussion with Cameron: 
![image](https://user-images.githubusercontent.com/4431065/52583330-919c9280-2dec-11e9-8949-ef568b866fa9.png)

**Comment by michaelmendoza** [comment]
Featured added. But no longer used.
